package/libhttpserver: needs gcc >= 5
libhtpserver uses the following constructor since version 0.18.0 and
https://github.com/etr/libhttpserver/commit/9cdc90177e12902adf4063300fd688fcfdbe8168:

http_request(http_request&& b) noexcept = default;

This raises the following build failure on gcc 4.8:

In file included from http_request.cpp:22:0:
httpserver/http_request.hpp:234:9: error: function 'httpserver::http_request::http_request(httpserver::http_request&&)' defaulted on its first declaration with an exception-specification that differs from the implicit declaration 'httpserver::http_request::http_request(httpserver::http_request&&)'
         http_request(http_request&& b) noexcept = default;
         ^

This build failure is due to the following gcc bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59526

Instead of adding BR2_TOOLCHAIN_HAS_GCC_BUG_59526, simply add a
dependency on gcc >= 5

Fixes:
 - http://autobuild.buildroot.org/results/18a29056e0191d9f23e1f9c6f72b13c07d03b300/

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>
Signed-off-by: Yann E. MORIN <yann.morin.1998@free.fr>